[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
    -I include
    -DEDGEGATE_VERSION=\"1.0\"
    -DCORE_DEBUG_LEVEL=1
    -DEVENT_BUFFER_CAPACITY=1024
    -DDNS_CACHE_SIZE=512
lib_deps =
    bblanchon/ArduinoJson@^7.3.0
test_framework = unity
test_build_src = yes

[platformio]
default_envs = esp32-c3-supermini
